name: Add new Chart

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install chart-releaser
        uses: engineerd/configurator@v0.0.10
        with:
          name: cr
          url: https://github.com/helm/chart-releaser/releases/download/v1.6.1/chart-releaser_1.6.1_linux_amd64.tar.gz
          pathInArchive: cr

      - name: Download new Chart
        run: |
          mkdir -p packages
          cd packages
          wget -q https://github.com/${{github.repository}}/releases/download/${{github.event.release.name}}/${{github.event.release.name}}.tgz
          ls -alh

      - name: Update Helm Index
        run: cr index
        env:
          CR_OWNER: "${{github.repository_owner}}"
          CR_TOKEN: "${{secrets.GITHUB_TOKEN}}"
          CR_GIT_REPO: "${{github.event.repository.name}}"
          CR_PACKAGE_PATH: packages
          CR_PAGES_BRANCH: main
          CR_PAGES_INDEX_PATH: docs/index.yaml
          CR_INDEX_PATH: docs/index.yaml

      - name: Commit changes
        run: |
          git add .
          git commit -m"add release ${{github.event.release.name }}"
          git push